### ISSUE TITLE
Login Page is Blank (1.6.0)

### ISSUE THREAD

**Issue by jholl016** [ironmansoftware/universal-dashboard#147]
Just starting to play around with this and I can't get the Login page sample code to work.  Here's what I am running:
```
$FormLogin = New-UDAuthenticationMethod -Endpoint {
    param([PSCredential]$Credentials)

    if ($Credentials.UserName -eq "User" -and $Credentials.GetNetworkCredential().Password -eq "Password") {
        New-UDAuthenticationResult -Success -UserName "User"
    } else {
        New-UDAuthenticationResult -ErrorMessage 'Invalid Logon Credentials'
    }
}

$LoginPage = New-UDLoginPage -AuthenticationMethod @($FormLogin)

$MyDashboardPage = New-UDPage -Url "/myDashboard" -Endpoint {
    New-UDCard -Title "Welcome, $User" -Text "This is your custom dashboard."
}

$Dashboard = New-UDDashboard -LoginPage $LoginPage -Page @(
    $MyDashboardPage
)

Start-UDDashboard -Port 80 -Dashboard $Dashboard -AllowHttpForLogin
```

Command line output is:
```
WARNING: Allowing logins over HTTP is insecure. This setting should only be used for development purposes.

Name        Port Running
----        ---- -------
Dashboard10   80    True
```

When I navigate to http://localhost, the URL correctly redirects to http://localhost/login, but the loaded page is completely blank, just a solid white nothing. I've tried multiple browsers.  Am I missing a required component?

**Comment by adamdriscoll** [comment]
This is a bug. I reproduced this issue as well. This failed in integration due to browser caching. I'll be releasing a 1.6.1 to resolve this shortly.

**Comment by adamdriscoll** [comment]
Fixed in 1.6.1

**Comment by ChrisMagnuson** [comment]
This is still happening for me in 1.6.1, PowerShell version 5.1. Redirects but page is blank.

**Comment by adamdriscoll** [comment]
@ChrisMagnuson Can you do a hard refresh in your browser (Ctrl+F5) and try again?

**Comment by ChrisMagnuson** [comment]
Ouch, user error, thank you, hard refresh worked.
