### ISSUE TITLE
Session Variables not working with PSVersion 5.0.10586.117...v1.6.1

### ISSUE THREAD

**Issue by RCDS1** [ironmansoftware/universal-dashboard#159]
Using the Session Variables examples here: https://adamdriscoll.gitbooks.io/powershell-universal-dashboard/content/v160.html  I am not returning the values in the example. 

![session](https://user-images.githubusercontent.com/39102853/39888881-b5d19fc4-5485-11e8-8349-3a3f51279e9f.jpg)

**Comment by adamdriscoll** [comment]
Can you enable logging and try again? 

Just call: `Enable-UDLogging` and it should output to the command window.

**Comment by RCDS1** [comment]
@adamdriscoll  do you need anymore information?

**Comment by adamdriscoll** [comment]
When you produced this log, did you try clicking on the filtering options? It seems like they should have been logged but something could be wrong.

**Comment by RCDS1** [comment]
Yes, nothing is logged when clicking on the filtering options. 

Do you need me to perform any other actions?

**Comment by adamdriscoll** [comment]
Can you look in the developer tools for your browser? Press F12 and see if there are any errors in the console view.

**Comment by RCDS1** [comment]
When clicking on the Session Options;

SyntaxError: Invalid character
   {
      [functions]: ,
      __proto__: {
         [functions]: ,
         __proto__: {
            [functions]: ,
            __proto__: {
               [functions]: ,
               __proto__: null
            },
            message: "",
            name: "Error"
         },
         message: "",
         name: "SyntaxError"
      },
      description: "Invalid character",
      message: "Invalid character",
      name: "SyntaxError",
      number: -2146827274,
      stack: "SyntaxError: Invalid character
   at Anonymous function (http://localhost:10003/main.c8bd73f2d3c8dd91eb33.bundle.js:106:194078)"
   }

SyntaxError: Invalid character
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid character",
      message: "Invalid character",
      name: "SyntaxError",
      number: -2146827274,
      stack: "SyntaxError: Invalid character
   at Anonymous function (http://localhost:10003/main.c8bd73f2d3c8dd91eb33.bundle.js:106:194078)"
   }

SyntaxError: Invalid character
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid character",
      message: "Invalid character",
      name: "SyntaxError",
      number: -2146827274,
      stack: "SyntaxError: Invalid character
   at Anonymous function (http://localhost:10003/main.c8bd73f2d3c8dd91eb33.bundle.js:106:194078)"
   }

**Comment by RCDS1** [comment]
When selecting a character...Line 200.. val = this.refs.element.selectedOptions[0].value  {exception}	Unable to get property '0' of undefined or null reference

import React from 'react';
import createReactClass from 'create-react-class';
import renderComponent from './render-service.jsx';
import PubSub from 'pubsub-js';
import {fetchGet} from './services/fetch-service.jsx';
import {getApiPath} from 'config';
import ReactInterval from 'react-interval';
import ErrorCard from './error-card.jsx';

export default class UdElement extends React.Component {
    constructor() {
        super();

        this.state = {
            hidden: false
        }
    }

    componentWillMount() {
        this.pubSubToken = PubSub.subscribe(this.props.id, this.onIncomingEvent.bind(this));
    }

    onIncomingEvent(eventName, event) {
        if (event.type === "removeElement") {
            this.setState({
                hidden: true
            })
        }
    }

    componentDidUpdate() {
        if (this.state.hidden) {
            PubSub.unsubscribe(this.pubSubToken);
        }
    }

    componentWillUnmount() {
        PubSub.unsubscribe(this.pubSubToken);
    }

    render() {   
        if (this.state.hidden) {
            return null;
        }
        return <UDElementContent {...this.props} />
    }
}

class UDElementContent extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            content : props.content,
            tag : props.tag,
            attributes: props.attributes,
            events: props.events,
            loading: true,
            hasError: false,
            errorMessage: ''
        }
    }

    loadData()
    { 
        fetchGet("/component/element/" + this.props.id, function(data) {
            if (data.error) {
                this.setState({
                    hasError: true, 
                    errorMessage: data.error.message
                })
                return;
            }

            this.setState({
                content: data,
                loading: false
            });
        }.bind(this));
    }

    componentDidCatch(error, info) {
        this.setState({ hasError: true, errorMessage: error.message });
    }

    componentWillMount() {
        this.pubSubToken = PubSub.subscribe(this.props.id, this.onIncomingEvent.bind(this));
        if (this.props.js) {
            $.getScript(getApiPath() + "/js/" + this.props.js, function() {
                this.setState({
                    loading: false
                })
            }.bind(this));
        }
        else {
            if (this.props.hasCallback) {
                this.loadData();
            }
            else 
            {
                this.setState({
                    loading: false
                })
            }
        }
    }

    componentDidMount() {
        if (this.state.tag === 'input' && this.state.attributes != null && this.state.attributes["type"] === 'text') {
            Materialize.updateTextFields();
        }
        
        $('.collapsible').collapsible();
        $('.modal').modal();

        if (this.state.tag === 'select') {
            $(this.refs.element).material_select(this.onUserEvent.bind(this));
        }
    }

    componentDidUpdate() {
        if (this.state.tag === 'input' && this.state.attributes != null && this.state.attributes["type"] === 'text') {
            Materialize.updateTextFields();
        }
    }

    onTextboxChanged(e) {
        var val = e.target.value;
        this.state.attributes.value = val;

        this.setState({
            attributes : this.state.attributes
        });
    }

    onCheckboxChanged(e) {
        var val = e.target.value;
        val = e.target.checked;
        this.state.attributes.checked = val;

        this.setState({
            attributes : this.state.attributes
        });

        for(var i = 0; i < this.state.events.length; i++) {
            if (this.state.events[i].event === 'onChange') {
                PubSub.publish('element-event', {
                    type: "clientEvent",
                    componentId: this.props.id,
                    eventName: 'onChange',
                    eventData: val
                });
            }
        }
    }

    componentWillUnmount() {
        PubSub.unsubscribe(this.pubSubToken);
    }

    onIncomingEvent(eventName, event) {
        if (event.type === "setState") {
            this.setState(event.state);
        }
        else if (event.type === "requestState") {
            PubSub.publish('element-event', {
                type: "requestStateResponse",
                state: this.state,
                requestId: event.requestId
            });
        } else if (event.type === "removeElement") {
            this.setState({
                hidden: true
            })
        } else if (event.type === "addElement") {

            var content = this.state.content;
            if (content == null) {
                content = []
            }

            content = content.concat(event.elements);

            this.setState({
                content
            })
        } else if (event.type === "clearElement") {
            this.setState({
                content: null
            })
        } else if (event.type === "syncElement") {
            this.loadData();
        }
    }

    onUserEvent(eventName, e) {

        var val = null;
        if (this.state.tag === 'select') {
            val = this.refs.element.selectedOptions[0].value
            eventName = 'onChange'
        }
        else {
            val = e.target.value;
            if (val != null && val.checked != null) {
                val = e.target.checked;
            }
        }

        this.state.attributes.value = val;
        this.setState(this.state);

        PubSub.publish('element-event', {
            type: "clientEvent",
            componentId: this.props.id,
            eventName: eventName,
            eventData: val
        });
    }

    render() {
        if (this.state.hidden) {
            return null;
        }

        if (this.state.hasError) {
            return <ErrorCard message={this.state.errorMessage} />
        }

        if (this.props.error) {
            return <ErrorCard message={this.props.error.message} />
        }

        if (this.state.loading) {
            return <div></div>
        }

        if (this.props.js) {
            return React.createElement(eval(this.props.moduleName + "." + this.props.componentName), this.props.props);
        }

        var children = null;
        
        if (this.state.content) {
            children = this.state.content.map(function(x) {
                if (x.type != null) {
                    return renderComponent(x, this.props.history);
                } 
                return x;
            }.bind(this));
        }

        var attributes = this.state.attributes;

        if (attributes == null) {
            attributes = {}
        }

        if (attributes.id == null) {
            attributes.id = this.props.id;
        }

        if (this.state.events != null) {
            this.state.events.map(function(event) {
                attributes[event.event] = function(e) {
                    this.onUserEvent(event.event, e);
                }.bind(this);
                return null;
            }.bind(this));
        }

        if (this.state.tag === "input") {
            if (attributes.type === "text") {
                attributes.onChange = this.onTextboxChanged.bind(this);
            }

            if (attributes.type === "checkbox") {
                attributes.onChange = this.onCheckboxChanged.bind(this);
            }
        }

        if (this.state.tag === "textarea") {
            attributes.onChange = this.onTextboxChanged.bind(this);
        }

        attributes.ref = 'element';
        attributes.key = this.props.id;

        this.element = React.createElement(this.state.tag, attributes, children);

    return [this.element, 
            <ReactInterval timeout={this.props.refreshInterval * 1000} enabled={this.props.autoRefresh} callback={this.loadData.bind(this)}/>];
    }
}


// WEBPACK FOOTER //
// ./src/app/ud-element.jsx

**Comment by adamdriscoll** [comment]
Ah, yeah. I see now. It's an issue with IE. I will get this fixed for 1.6.2. It looks like the Chrome works. Can you try there?

**Comment by adamdriscoll** [comment]
This was actually a pretty easy fix in the client code. It has been resolved for 1.6.2.

**Comment by RCDS1** [comment]
@adamdriscoll  i'm still seeing this issue. This error is in firefox

![index operation failed](https://user-images.githubusercontent.com/39102853/41549596-edce39ba-7315-11e8-9760-a23db2883eef.jpg)
