### ISSUE TITLE
Icons are not displayed on buttons with 2.4 update

### ISSUE THREAD

**Issue by SConstantinou** [ironmansoftware/universal-dashboard#819]
After upgrading to 2.4 icons on buttons are not displayed.

New-UDButton -Icon play

**Comment by adamdriscoll** [comment]
This has been resolved in PR #816

**Comment by wsl2001** [comment]
Issue resolved on locally running dashboard but its still the same if you run the dashboard in IIS.

**Comment by adamdriscoll** [comment]
No issue here in IIS. 

![image](https://user-images.githubusercontent.com/1256531/58266361-bcc54500-7d3e-11e9-8b78-a9c964ab5984.png)
