### ISSUE TITLE
1.6 beta2 : Dynamic page doesn't work anymore

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/universal-dashboard#96]
Adam,

On a dashboard I have a page that contains a form associated with a dynamic page. When the user press the Submit button on the form, the values of the different form fields are sent to a dynamic form that shows a recap to the user. On this dynamic form, the user can review the input values and then can click on two buttons (Continue or Cancel).

It worked fine with 1.5.x but not anymore with 1.6 betas. Now when the user click on the submit button, the dynamic form is called (I can see the header title) but I have and endless hourglass or something. I enabled the debug logs but I cannot see anything relevant.

This is an extract of the logs:
```
23:15:22 ExecutionService StackTrace = 
23:15:22 ExecutionService StateRequestService = PowerShellProTools.UniversalDashboard.Services.StateRequestService
23:15:22 ExecutionService str = %7b%22TitreRecherche%22%3a%22Annonces+Goldwing%22%2c%22MotsCles%22%3a%22goldwing%22%2c%22Rechercher_Dans_Titre_Uniquement%22%3atrue%2c%22PrixMin%22%3a%220%22%2c%22PrixMax%22%3a%226000%22%2c%22CodePostal%22%3anull%2c%22Particuliers_Ou_Pros%22%3a2%2c%22Categorie%22%3a%22Motos%22%2c%22Region%22%3a%22Aquitaine%22%2c%22Departement%22%3a%22Gironde%22%7d
23:15:22 ExecutionService take = 10
23:15:22 ExecutionService Text = Essai
23:15:22 ExecutionService TitreRecherche = Annonces Goldwing
23:15:22 ExecutionService TortoiseGitSettings = @{TortoiseGitCommands=System.Collections.Hashtable; TortoiseGitPath=C:\Program Files\TortoiseGit\bin\TortoiseProc.exe}
23:15:22 ExecutionService User = Arnaud Petitjean
23:15:22 ExecutionService userEmail = apetitje@gmail.com
23:15:22 ExecutionService VcsPromptStatuses = System.Object[]
23:15:22 ExecutionService VerbosePreference = SilentlyContinue
23:15:22 ExecutionService WarningPreference = Continue
23:15:22 ExecutionService WebServer = ws2012r2us-1.cloudapp.net:8080
23:15:22 ExecutionService WhatIfPreference = False
23:15:22 ExecutionService Context variables--------------
23:15:22 ExecutionService Request = Microsoft.AspNetCore.Http.Internal.DefaultHttpRequest
23:15:22 ExecutionService Response = Microsoft.AspNetCore.Http.Internal.DefaultHttpResponse
23:15:22 ExecutionService User = Arnaud Petitjean
23:15:22 ExecutionService MemoryCache = Microsoft.Extensions.Caching.Memory.MemoryCache
23:15:22 ComponentController System.Object[]
23:15:22 Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor Executing JsonResult, writing value System.Object[].
23:15:22 Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action PowerShellProTools.UniversalDashboard.Controllers.ComponentController.Input (PowerShellProTools.UniversalDashboard) in 728.9142ms
23:15:22 Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 741.0798ms 200 application/json; charset=utf-8
23:15:22 ExecutionService ExecutionService constructor
23:15:45 Quartz.Core.QuartzSchedulerThread Batch acquisition of 0 triggers
23:15:56 GetDashboardCommand Name: 
23:15:56 StopDashboardCommand ByServer
23:15:57 ExecutionService ExecutionService constructor
23:15:57 Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport 04/23/2018 23:15:57: Connection Id ed70a6e4-8085-4940-a61c-f8bff0e91623: Socket closed.
23:15:57 Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 1465326.4797ms 101 
23:15:57 Quartz.Core.QuartzScheduler Scheduler QuartzScheduler_$_NON_CLUSTERED shutting down.
23:15:57 Quartz.Core.QuartzScheduler Scheduler QuartzScheduler_$_NON_CLUSTERED paused.
23:15:57 Quartz.Simpl.TaskSchedulingThreadPool Shutting down threadpool...
23:15:57 Quartz.Simpl.TaskSchedulingThreadPool Shutdown of threadpool complete.
23:15:57 Quartz.Core.QuartzScheduler Scheduler QuartzScheduler_$_NON_CLUSTERED Shutdown complete.

```

**Comment by adamdriscoll** [comment]
@apetitjean No good! I will look into it. If you have a minimal reproduction of the issue, that would be helpful.

**Comment by apetitjean** [comment]
Here it is: 

```PowerShell

Import-Module UniversalDashboard



$EndpointInitializationScript = {
  
    function New-UDButton {
        param(
            [Parameter()]
            [String]$Id = (New-Guid),
            [Parameter()]
            $Text,
            [Parameter()]
            [ScriptBlock]$OnClick,
            [Parameter()]
            [Switch]$Floating,
            [Parameter()]
            [Switch]$Flat,
            [Parameter()]
            [PowerShellProTools.UniversalDashboard.Models.FontAwesomeIcons]$Icon,
            [Parameter()]
            [ValidateSet('left', 'right')]
            [String]$IconAlignment = 'left'
        )

        $btnClass = 'btn'
        if ($Floating) {
            $btnClass = 'btn-floating'
        }

        if ($Flat) {
            $btnClass = 'btn-flat'
        }

        New-UDElement -Id $Id -Tag "a" -Attributes @{
            className = "$btnClass"
            onClick = $OnClick
        } -Content {
            if ($Icon -ne $null) {
                $faClass = $Icon.ToString().Replace('_', '-')
                New-UDElement -Tag 'i' -Attributes @{ className = "fa fa-$faClass $iconAlignment" }
            }

            $Text
        }
    }

    function New-UDHeading {
        param(
            [Parameter()]
            [String]$Id = (New-Guid),
            [Parameter()]
            $Content,
            [Parameter()]
            [ValidateSet("1", "2", "3", "4", "5", "6")]
            $Size,
            [Parameter()]
            [PowerShellProTools.UniversalDashboard.Models.DashboardColor]$Color = 'black'
        )

        New-UDElement -Id $Id -Tag "h$size" -Content {
            $Content
        } -Attributes @{
            style = @{
                color = $Color.HtmlColor
            }
        }
    }

    $CouleurTitre = '#ee6e73'


}




$DynamicPage1 = New-UDPage -Url "/dynamic/:text" -Endpoint {
    param($text)

    $params = [System.Web.HttpUtility]::UrlDecode($text) | ConvertFrom-Json

    New-UDRow -Columns {
        New-UDColumn -Size 12 -Content {
            New-UDHeading -Size 4 -Content "Please check the values before submitting them" -Color '#ee6e73'
            }
    }

    New-UDRow -Columns {
        New-UDColumn -Size 1  -Content {}
        New-UDColumn -Size 8 -Content {
            New-UDElement -Tag "P" -Content { "{0} : {1}" -f 'Title', $params.Title } 
            New-UDElement -Tag "P" -Content { "{0} : {1}" -f 'Keywords', $params.keywords }
            New-UDElement -Tag "P" -Content { "{0} : {1}" -f 'Search only in title', $params.SearchInTitleOnly }
            New-UDElement -Tag "P" -Content { "{0} : {1}" -f 'ZipCode', $params.ZipCode }
        }
    }

    New-UDLayout -Columns 2 -Content {
        New-UDButton -Text 'OK' -OnClick { 
            & $onClickHandler1 
        } -Icon trademark

        New-UDButton -Text 'Cancel' -OnClick {  
            Set-UDElement -Id "ShowOnClick" -Content { "Cancelled!" }
        } 
    }

    New-UDRow -Columns {
        New-UDColumn -Content {
            New-UDHeading -Size 5 -Id 'ShowOnClick' -Color '#ee6e73' -Content ''
        }
    }

    $onClickHandler1 = {
            Set-UDElement -Id "ShowOnClick" -Content { "Your request has been recorded successfully" }
    }
    
}

$Page0 = New-UDPage -Name "Fill the form" -icon search `
                    -Content {
                        New-UDRow -Columns {
                            New-UDColumn -Size 12 -Endpoint {
                                New-UDInput -Title "Your search criteria" -Endpoint {
                                    [CmdletBinding()]
                                    param(
                                        $Title, 
                                        $Keywords, 
                                        [Bool]$SearchInTitleOnly,
                                        $ZipCode
                                    ) 

                                    $str = $pscmdlet.MyInvocation.BoundParameters
                                    $str = [System.Web.HttpUtility]::UrlEncode( ($str | ConvertTo-Json -Compress) )
                                    New-UDInputAction -RedirectUrl "/dynamic/$str"

                                    
                                } -Content {
                                    New-UDInputField -Name Title   -Type textbox -Placeholder "Enter a title" 
                                    New-UDInputField -Name Keywords         -Type textbox -Placeholder "Keyword to search for" 
                                    New-UDInputField -Name SearchInTitleOnly `
                                                     -Type checkbox `
                                                     -DefaultValue $false `
                                                     -Placeholder "Do the search only in the title"
                                    
                                    New-UDInputField -Name ZipCode       -Type textbox -Placeholder "ZipCode"
                                    
                                } #-FontColor "black"
                            }
                        }
                    }
                

$Dashboard = New-UDDashboard -Title "Show bug with dynamic page in 1.6 Beta"  `
                             -EndpointInitializationScript $EndpointInitializationScript `
                             -Pages @($Page0, $DynamicPage1)

Enable-UDLogging -Level Debug -FilePath .\log.txt -Console
Start-UDDashboard -Dashboard $Dashboard -Port 8081 -AllowHttpForLogin
```

**Comment by adamdriscoll** [comment]
@apetitjean Thanks for the repro! That made it very easy to track down. This has been fixed in 1.6.0-beta3.

![image](https://user-images.githubusercontent.com/1256531/39222100-678dc40a-4800-11e8-90d7-e399f57010a7.png)

**Comment by apetitjean** [comment]
@adamdriscoll, unfortunately it still doesn't work in 1.6.0-beta3... :(

```
22:30:24 Microsoft.AspNetCore.Sockets.Internal.Transports.WebSocketsTransport 04/26/2018 22:30:24: Connection Id f7a7e868-88c0-436e-91b7-f0af9087322d: Socket closed.
22:30:24 Microsoft.AspNetCore.Sockets.ConnectionManager 04/26/2018 22:30:24: ConnectionId f7a7e868-88c0-436e-91b7-f0af9087322d: Failed disposing connection.
22:30:24 Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 31501.6019ms 101
22:30:24 ComponentController System.Object[]
22:30:24 Microsoft.AspNetCore.Mvc.Formatters.Json.Internal.JsonResultExecutor Executing JsonResult, writing value System.Object[].
22:30:24 Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker Executed action PowerShellProTools.UniversalDashboard.Controllers.ComponentController.Input (PowerShellPr
22:30:24 Microsoft.AspNetCore.Hosting.Internal.WebHost Request finished in 665.2106ms 200 application/json; charset=utf-8
```

**Comment by apetitjean** [comment]
You rocks @adamdriscoll !! That was it! Thanks 😃
